apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudproject-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudproject-backend
  template:
    metadata:
      labels:
        app: cloudproject-backend
    spec:
      containers:
      - name: cloudproject-backend
        image: zoseregistry.azurecr.io/cloudproject-backend:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: cloudproject-backend
spec:
  selector:
    app: cloudproject-backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudproject-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudproject-frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: cloudproject-frontend
        image: zoseregistry.azurecr.io/cloudproject-frontend:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: cloudproject-frontend
spec:
  selector:
    app: cloudproject-frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
