version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "5000:5000"
    volumes:
      - ./back:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    depends_on:
      - backend
